[project]
name = "advent-of-code"
version = "2.1.0"
description = "Advent of Code CLI Tool"
authors = [{name = "heavycircle"}]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.30",
    "typer>=0.20.0"
]

[project.scripts]
aoc = "cli.cli:app"
